name: phpunit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install composer dependencies
      run: composer install --prefer-dist

    - name: Install npm dependencies
      run: npm install

    - name: Run Mix
      run: npm run production

    - name: Run PHPUnit
      run: php7.3 vendor/bin/phpunit
